apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datastore-exporter.fullname" . }}-config
  labels:
    {{- include "datastore-exporter.labels" . | nindent 4 }}
data:
  datastore-exporter.toml: |
    [log]
    verbose = true
    console = false
    [gcs]
    projectID = {{ .Values.gcloud.project | quote }}
    bucketName = {{ .Values.gcloud.bucket | quote }}
