apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "datastore-exporter.fullname" . }}
  labels:
    {{- include "datastore-exporter.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: config
            configMap:
              name: {{ include "datastore-exporter.fullname" . }}-config
          - name: gcloud-credentials
            secret:
              secretName: {{ .Values.gcloud.serviceAccount.secretName }}
              items:
                - key: {{ .Values.gcloud.serviceAccount.key }}
                  path: {{ .Values.gcloud.serviceAccount.key }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/datastore-exporter/datastore-exporter.toml
              subPath: datastore-exporter.toml
            - name: gcloud-credentials
              mountPath: /etc/datastore-exporter/credentials.json
              readOnly: true
              subPath: {{ $.Values.gcloud.serviceAccount.key }}
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/datastore-exporter/credentials.json
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
